{
    'name': 'Rental Invoicing',
    'version': '1.0',
    'summary': 'Rental Summery',
    'description': 'Rental application',
    'category': 'Ride-Sharing',
    'sequence': -197,
    'author': 'Redon',
    'website': 'Website',
    'depends': ['base','booking'],
    'data': [
        'data/inv_pay_sequence.xml',
        'views/invoice_view.xml',
        'views/payment_view.xml',
        'wizard/invoice_payment_view.xml',
        'views/menu_view.xml',
    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
